name: Build and Deploy Functions when pushed to master
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install functions dependencies
        run: (cd functions && npm install)
      - name: Update Environment Variable
        uses: w9jds/firebase-action@master
        with:
          args: functions:config:set myenv.location="${{ secrets.SECRET_LOCATION }}"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}        
      - name: Install webapp dependencies
        run: npm install
      - name: Build Web App
        run: npm run build
        env:
          CI: ""
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
